# Generated by Django 2.2.4 on 2019-12-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxetime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
    ]
