# Generated by Django 2.2 on 2019-11-21 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('boxetime', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewCompetition',
            new_name='Competition',
        ),
    ]
