# Generated by Django 2.2 on 2019-11-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('boxetime', '0002_auto_20191122_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='docs',
            field=models.FileField(blank=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='sport',
            field=models.CharField(choices=[('Boxing', 'Бокс'), ('Kickboxing', 'Кикбоксинг')], default='Бокс',
                                   max_length=50),
        ),
        migrations.CreateModel(
            name='AddRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Doctor', 'Врач'), ('Participant', 'Участник'), ('Coach', 'Тренер'),
                                                   ('Sponsor', 'Cпонсор')], default='Участник', max_length=100)),
                ('weight', models.PositiveSmallIntegerField()),
                ('docs', models.FileField(blank=True, upload_to='docs/')),
                ('competit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxetime.Competition')),
            ],
        ),
    ]
