# Generated by Django 2.2.4 on 2019-12-24 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boxetime', '0003_auto_20191224_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='author',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to=settings.AUTH_USER_MODEL),
        ),
    ]
