# Generated by Django 2.2 on 2019-11-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boxetime', '0003_auto_20191124_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrequest',
            name='userid',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
