# Generated by Django 2.2.4 on 2020-02-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxetime', '0004_auto_20200207_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='users',
        ),
    ]
