# Generated by Django 2.2.4 on 2020-02-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxetime', '0005_remove_competition_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addrequest',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Врач'), ('Participant', 'Участник'), ('Coach', 'Тренер'), ('Sponsor', 'Cпонсор'), ('Referee', 'Судья')], default='Participant', max_length=100),
        ),
    ]
