# Generated by Django 2.2 on 2019-11-28 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('boxetime', '0005_auto_20191127_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrequest',
            name='acepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addrequest',
            name='userid',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
