# Generated by Django 2.2 on 2019-11-28 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boxetime', '0006_auto_20191128_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='responsible',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
