# Generated by Django 2.2.4 on 2020-02-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxetime', '0006_auto_20200213_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrequest',
            name='club',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
