# Generated by Django 2.2 on 2019-11-28 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boxetime', '0008_auto_20191128_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitgrid',
            name='winuser',
        ),
        migrations.AddField(
            model_name='competitgrid',
            name='memberwin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberwin',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
