# Generated by Django 2.2 on 2019-11-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('boxetime', '0009_auto_20191128_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitgrid',
            name='competitid',
        ),
        migrations.AddField(
            model_name='competition',
            name='competitid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='boxetime.CompetitGrid'),
        ),
    ]
